// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_pairwise_distances
NumericVector cpp_pairwise_distances(const NumericMatrix coordinates);
RcppExport SEXP _RiskMap_cpp_pairwise_distances(SEXP coordinatesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix >::type coordinates(coordinatesSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pairwise_distances(coordinates));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cross_distances
NumericMatrix cpp_cross_distances(const NumericMatrix first, const NumericMatrix second);
RcppExport SEXP _RiskMap_cpp_cross_distances(SEXP firstSEXP, SEXP secondSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix >::type first(firstSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type second(secondSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cross_distances(first, second));
    return rcpp_result_gen;
END_RCPP
}
// cpp_half_integer_matern
NumericVector cpp_half_integer_matern(const NumericVector distances, const double phi, const double kappa);
RcppExport SEXP _RiskMap_cpp_half_integer_matern(SEXP distancesSEXP, SEXP phiSEXP, SEXP kappaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type distances(distancesSEXP);
    Rcpp::traits::input_parameter< const double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const double >::type kappa(kappaSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_half_integer_matern(distances, phi, kappa));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RiskMap_cpp_pairwise_distances", (DL_FUNC) &_RiskMap_cpp_pairwise_distances, 1},
    {"_RiskMap_cpp_cross_distances", (DL_FUNC) &_RiskMap_cpp_cross_distances, 2},
    {"_RiskMap_cpp_half_integer_matern", (DL_FUNC) &_RiskMap_cpp_half_integer_matern, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_RiskMap(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
