# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_pairwise_distances <- function(coordinates) {
    .Call(`_RiskMap_cpp_pairwise_distances`, coordinates)
}

cpp_cross_distances <- function(first, second) {
    .Call(`_RiskMap_cpp_cross_distances`, first, second)
}

cpp_half_integer_matern <- function(distances, phi, kappa) {
    .Call(`_RiskMap_cpp_half_integer_matern`, distances, phi, kappa)
}

